### ISSUE TITLE
【抖音】BUG 重复发送消息

### ISSUE THREAD

**Issue by LouisDM** [cs-lazy-tools/ChatGPT-On-CS#26]
大模型返回有换行符内容的时候，多条消息触发了抖音的频繁发送消息提醒，软件把抖音提醒当成了用户信息，就一直发消息。
![image](https://github.com/cs-lazy-tools/ChatGPT-On-CS/assets/19233988/9c72fffc-7c4e-4c88-b46f-13ee0f58e929)

**Comment by lrhh123** [comment]
新版已经解决
