### ISSUE TITLE
企业微信无法使用

### ISSUE THREAD

**Issue by wenqing0928** [cs-lazy-tools/ChatGPT-On-CS#33]
企业微信不自动回复，日志报错
/
#
![微信图片_20240527150728](https://github.com/cs-lazy-tools/ChatGPT-On-CS/assets/133615491/b52b3ba2-9a0e-4fc0-83c8-3659f847b43b)
![2](https://github.com/cs-lazy-tools/ChatGPT-On-CS/assets/133615491/3ab30a33-673d-4bc6-93b5-8ba8d3a76c73)

**Comment by lrhh123** [comment]
fix: 新版已修复
