### ISSUE TITLE
接入LM STUDIO 的API 接口回复的问题前面带有 ？\n\n### Response:\n   这个几个回复 是系统默认的吗 

### ISSUE THREAD

**Issue by henrylaobai** [cs-lazy-tools/ChatGPT-On-CS#37]
操作平台 WIN 10 
客户端 微信 
接入API   

匹配不到关键词以后 能否忽略 这个 ？Response:  这个 自动回复的内容
use ： 你知道地球有多大 

以下是回复内容    
"content": "？\n\n### Response:\n根据科学家的测量，地球的平均直径约为12,742公里，而赤道周长大约40,075公里。然而，需要注意的是这些数据是近似的，因为地球是一个不规则的椭球体，所以实际大小会有些微差异。"

**Comment by lrhh123** [comment]
是的，新版本你可以通过插件去自定义这个模板，你估计使用的是 Dify 吧，Dify 默认的上下文机制非常奇葩，它无法通过传递全部文本的方式去处理上下文，而是需要先创建一个 session 再传递，我这里是省的去创建 Session
