### ISSUE TITLE
飞鸽客服页面自动回复无响应

### ISSUE THREAD

**Issue by CzyerChen** [cs-lazy-tools/ChatGPT-On-CS#38]
没有配置GPT情况，使用默认知识库自动关键词匹配回复
1、电商-勾选抖店
2、新开一个空chrome页面，再开了飞鸽客服页面
3、能够自动跳到当前会话
4、点击某一个对话框，对于用户输入“什么时候发货”，理想是应该匹配【时候and发货】做出自动回复，但是每次都发送默认回复，如果客服设置没有配置默认回复，就发不了。

<img width="1111" alt="image" src="https://github.com/cs-lazy-tools/ChatGPT-On-CS/assets/22817918/d693974f-70e2-4a8e-86be-2b1a6484a49e">

匹配是什么逻辑，应该如何配置？

**Comment by lrhh123** [comment]
fix: 已修复
