### ISSUE TITLE
VirusTotal detection of 1.0.2.exe 

### ISSUE THREAD

**Issue by NotTheD** [cs-lazy-tools/ChatGPT-On-CS#42]
One of virustotal agent is detected Trojan.Python.Spy.
Scan report avaible here: https://www.virustotal.com/gui/file/bc002658f6948390b6bf296bee4d1c0e8a88a7870d70793772dbaedf456fb7ff/detection

Maybe its false positive, but keep in mind since author (or developer) clarify this.
![iTYkE795k2](https://github.com/user-attachments/assets/8c18ec98-2d63-49a4-83aa-24285fd0fe2f)

**Comment by lrhh123** [comment]
为什么会报毒？ 没有具体原因吗？ 就因为打包了 Python 代码就说是木马病毒？？？ 
 
 Why is it being flagged as a virus? Is there no specific reason? Just because it includes packaged Python code, they are calling it a trojan virus???
